
[opener]
vlc = [
  # { run = 'flatpak run org.videolan.VLC "$@"', orphan = true, desc = "VLC Flatpak" }
  { run = 'vlc "$@"', orphan = true, desc = "VLC" }
]


zathura = [
  { run = 'zathura "$@"', orphan = true, desc = "Zathura PDF Reader" }
]

nsxiv = [
  { run = 'nsxiv "$@"', orphan = true, desc = "nsxiv Image Viewer" }
]

[open]
rules = [
  { mime = "video/*", use = ["vlc"] },
  { mime = "application/pdf", use = ["zathura"] },
  { mime = "image/*", use = ["nsxiv"] }
]
